FROM r-base:4.2.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    sudo \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libxml2-dev \
    libpoppler-cpp-dev \
    openjdk-17-jdk \
    cmake \
    && rm -rf /var/lib/apt/lists/*

ENV R_REMOTES_NO_ERRORS_FROM_WARNINGS="false"

RUN R -e "options(warn = 2); install.packages('remotes')"
RUN R -e "options(warn = 2); install.packages('RCurl')"
RUN R -e "options(warn = 2); require('remotes'); install_version('DBI', version = '1.1.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('DiceDesign', version = '1.9', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('GPfit', version = '1.0-8', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('KernSmooth', version = '2.23-20', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('MASS', version = '7.3-58.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('Matrix', version = '1.5-3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('R6', version = '2.5.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('RColorBrewer', version = '1.1-3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('RSQLite', version = '2.2.18', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('Rcpp', version = '1.0.9', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('RcppTOML', version = '0.1.7', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('SQUAREM', version = '2021.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('SnowballC', version = '0.7.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('askpass', version = '1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('assertthat', version = '0.2.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('backports', version = '1.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('base64enc', version = '0.1-3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('bit', version = '4.0.5', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('bit64', version = '4.0.5', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('blob', version = '1.2.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('broom', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('bslib', version = '0.4.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('cachem', version = '1.0.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('callr', version = '3.7.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('cellranger', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('class', version = '7.3-20', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('cli', version = '3.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('clipr', version = '0.8.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('clock', version = '0.6.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('codetools', version = '0.2-18', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('colorspace', version = '2.0-3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('config', version = '0.3.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('conflicted', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('cpp11', version = '0.4.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('crayon', version = '1.5.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('curl', version = '4.3.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('data.table', version = '1.14.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('dbplyr', version = '2.2.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('dials', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('digest', version = '0.6.30', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('dplyr', version = '1.0.10', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('dtplyr', version = '1.2.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('ellipsis', version = '0.3.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('evaluate', version = '0.16', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fansi', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('farver', version = '2.1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fastmap', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('forcats', version = '0.5.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('foreach', version = '1.5.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fs', version = '1.5.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fst', version = '0.9.8', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fstcore', version = '0.9.12', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('furrr', version = '0.3.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('future', version = '1.29.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('future.apply', version = '1.10.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('fuzzyjoin', version = '0.1.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('gargle', version = '1.2.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('generics', version = '0.1.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('geosphere', version = '1.5-14', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('ggplot2', version = '3.4.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('globals', version = '0.16.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('glue', version = '1.6.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('googledrive', version = '2.0.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('googlesheets4', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('gower', version = '1.0.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('gtable', version = '0.3.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('hardhat', version = '1.2.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('haven', version = '2.5.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('here', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('highr', version = '0.9', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('hms', version = '1.1.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('htmltools', version = '0.5.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('httr', version = '1.4.4', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('ids', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('infer', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('ipred', version = '0.9-13', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('isoband', version = '0.2.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('iterators', version = '1.0.14', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('janitor', version = '2.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('jquerylib', version = '0.1.4', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('jsonlite', version = '1.8.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('keras', version = '2.9.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('knitr', version = '1.40', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('labeling', version = '0.4.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('lattice', version = '0.20-41', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('lava', version = '1.7.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('lhs', version = '1.1.5', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('lifecycle', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('listenv', version = '0.8.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('lubridate', version = '1.9.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('magrittr', version = '2.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('memoise', version = '2.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('mgcv', version = '1.8-41', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('mime', version = '0.12', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('modeldata', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('modelenv', version = '0.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('modelr', version = '0.1.9', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('munsell', version = '0.5.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('nlme', version = '3.1-160', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('nnet', version = '7.3-18', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('numDeriv', version = '2016.8-1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('openssl', version = '2.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('parallelly', version = '1.32.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('parsnip', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('patchwork', version = '1.1.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('pillar', version = '1.8.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('pkgconfig', version = '2.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('plogr', version = '0.2.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('png', version = '0.1-7', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('prettyunits', version = '1.1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('processx', version = '3.8.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('prodlim', version = '2019.11.13', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('progress', version = '1.2.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('progressr', version = '0.11.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('ps', version = '1.7.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('purrr', version = '0.3.5', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rappdirs', version = '0.3.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('readr', version = '2.1.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('readxl', version = '1.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('recipes', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rematch', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rematch2', version = '2.1.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('renv', version = '0.16.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('reprex', version = '2.0.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('reticulate', version = '1.26', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rlang', version = '1.0.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rmarkdown', version = '2.16', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rpart', version = '4.1.19', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rprojroot', version = '2.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rsample', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rstudioapi', version = '0.14', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('rvest', version = '1.0.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('sass', version = '0.4.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('scales', version = '1.2.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('selectr', version = '0.4-2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('slider', version = '0.3.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('snakecase', version = '0.11.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('sp', version = '1.5-0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('stringdist', version = '0.9.8', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('stringi', version = '1.7.8', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('stringr', version = '1.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('survival', version = '3.4-0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('sys', version = '3.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tensorflow', version = '2.9.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('textrecipes', version = '1.0.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tfautograph', version = '0.3.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tfruns', version = '1.5.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tibble', version = '3.1.8', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tictoc', version = '1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tidymodels', version = '1.0.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tidyr', version = '1.2.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tidyselect', version = '1.2.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tidytable', version = '0.9.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tidyverse', version = '1.3.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('timeDate', version = '4021.106', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('timechange', version = '0.1.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tinytex', version = '0.42', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tokenizers', version = '0.2.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tune', version = '1.0.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('tzdb', version = '0.3.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('utf8', version = '1.2.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('uuid', version = '1.1-0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('vctrs', version = '0.5.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('viridisLite', version = '0.4.1', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('vroom', version = '1.5.7', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('warp', version = '0.2.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('whisker', version = '0.4', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('withr', version = '2.5.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('workflows', version = '1.1.2', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('workflowsets', version = '1.0.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('xfun', version = '0.33', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('xml2', version = '1.3.3', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('yaml', version = '2.3.6', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('yardstick', version = '1.1.0', repos = 'http://cran.r-project.org')"
RUN R -e "options(warn = 2); require('remotes'); install_version('zeallot', version = '0.1.0', repos = 'http://cran.r-project.org')"